In [186]:
import pandas as pd

pd.set_option('display.max_columns', None)  # or 1000
pd.set_option('display.max_rows', None)  # or 1000
pd.set_option('display.max_colwidth', None)  # or 199

In [162]:
population_by_county = pd.read_csv("hispanic_by_county/DECENNIALPL2020.P2_data_with_overlays_2021-12-12T053118.csv")

In [163]:
population_by_county.head()

,GEO_ID,NAME,P2_001N,P2_002N,P2_003N,P2_004N,P2_005N,P2_006N,P2_007N,P2_008N,...,P2_064N,P2_065N,P2_066N,P2_067N,P2_068N,P2_069N,P2_070N,P2_071N,P2_072N,P2_073N
0,id,Geographic Area Name,!!Total:,!!Total:!!Hispanic or Latino,!!Total:!!Not Hispanic or Latino:,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...
1,0500000US01001,"Autauga County, Alabama",58805,2117,56688,54198,41582,11352,184,873,...,0,0,0,0,0,0,0,0,0,0
2,0500000US01003,"Baldwin County, Alabama",231767,12686,219081,208713,186495,18001,1291,2029,...,0,0,0,0,0,0,0,0,0,0
3,0500000US01005,"Barbour County, Alabama",25223,1510,23713,23160,11086,11850,58,103,...,0,2,2,0,0,0,0,0,0,0
4,0500000US01007,"Bibb County, Alabama",22293,740,21553,20953,16442,4390,39,26,...,0,0,0,0,0,0,0,0,0,0

In [164]:
population_by_county = population_by_county[["GEO_ID", "NAME", "P2_001N", "P2_002N"]][1:]

In [165]:
population_by_county.head()

           GEO_ID                     NAME P2_001N P2_002N
1  0500000US01001  Autauga County, Alabama   58805    2117
2  0500000US01003  Baldwin County, Alabama  231767   12686
3  0500000US01005  Barbour County, Alabama   25223    1510
4  0500000US01007     Bibb County, Alabama   22293     740
5  0500000US01009   Blount County, Alabama   59134    5771

In [166]:
def get_county(geo_id):
    try:
        return geo_id.split("US")[1]
    except:
        return "NA"

In [167]:
population_by_county['county'] = population_by_county.GEO_ID.apply(lambda geo_id: get_county(geo_id))

In [213]:
population_by_county.head()

           GEO_ID                     NAME P2_001N P2_002N county
1  0500000US01001  Autauga County, Alabama   58805    2117  01001
2  0500000US01003  Baldwin County, Alabama  231767   12686  01003
3  0500000US01005  Barbour County, Alabama   25223    1510  01005
4  0500000US01007     Bibb County, Alabama   22293     740  01007
5  0500000US01009   Blount County, Alabama   59134    5771  01009

In [206]:
population_by_county.to_csv('data/population_by_county.csv', index=False)

In [183]:
def get_election_result(year, county_id):
    url = "https://uselectionatlas.org/RESULTS/statesub.php?year={year}&fips={county_id}&f=0&off=0&elect=0".format(year=year, county_id=county_id)
    r = requests.get(url)
    results = pd.read_html(r.text)[1]
    last_col = len(results.columns)-1
    
    popular_vote_pop = "Unnamed: " + str(last_col-1)
    popular_vote_perc = "Unnamed: " + str(last_col)
    try:
        results.rename(columns={'PoliticalParty': 'party',
                            'PresidentialCandidate': 'candidate',
                            'Vice PresidentialCandidate': 'vp',
                           popular_vote_pop: 'popular_vote_pop',
                           popular_vote_perc: 'popular_vote_perc'}, inplace=True)
        results = results.loc[:, ["candidate", "party", "popular_vote_pop", "popular_vote_perc"]]

        if (results.loc[0, 'party'] == 'Democratic') {
            dem_candidate = [results.loc[0, 'candidate']], 
            dem_vote = [results.loc[0, 'popular_vote_pop']],
            demo_score = [results.loc[0, 'popular_vote_perc']]
            
            rep_candidate= [results.loc[1, 'candidate']], 
            rep_vote= [results.loc[1, 'popular_vote_pop']],
            rep_score= [results.loc[1, 'popular_vote_perc']]
        } else {
            dem_candidate = [results.loc[1, 'candidate']], 
            dem_vote = [results.loc[1, 'popular_vote_pop']],
            demo_score = [results.loc[1, 'popular_vote_perc']]
            
            rep_candidate= [results.loc[0, 'candidate']], 
            rep_vote= [results.loc[0, 'popular_vote_pop']],
            rep_score= [results.loc[0, 'popular_vote_perc']]
        }
        return {'year': [year],
                'county': [county_id],
                ,
                
               }
    except:
        return {'year': [year],
                'county': [county_id],
                'dem_candidate': ['NA'], 
                'dem_vote': ['NA'],
                'dem_score': ['NA'],
                'rep_candidate': ['NA'], 
                'rep_vote': ['NA'],
                'rep_score': ['NA']}

In [ ]:
county_ids = population_by_county.county
election_results = pd.DataFrame()
for year in [2016, 2020]:
    for county_id in county_ids:
        print('%s - %s' % (year, county_id))
        res_in_county = get_election_result(year, county_id)
        
        election_results = pd.concat([election_results, pd.DataFrame(res_in_county)])

In [221]:
election_results = pd.read_csv("data/election_results.csv")

In [222]:
election_results.head()

,year,county,dem_candidate,dem_vote,dem_score,rep_candidate,rep_vote,rep_score
0,2016,1001,Donald J. Trump,18172.0,72.77%,Hillary Clinton,5936.0,23.77%
1,2016,1003,Donald J. Trump,72883.0,76.55%,Hillary Clinton,18458.0,19.39%
2,2016,1005,Donald J. Trump,5454.0,52.10%,Hillary Clinton,4871.0,46.53%
3,2016,1007,Donald J. Trump,6738.0,76.40%,Hillary Clinton,1874.0,21.25%
4,2016,1009,Donald J. Trump,22859.0,89.33%,Hillary Clinton,2156.0,8.43%

In [212]:
election_results.to_csv("data/election_results.csv", index=False)

In [ ]:
election_results.loc[0, "year"]

In [196]:
def dem_results(df):
    def dem_result(data, col="candidate"):
        if (data == "Hillary Clinton") or (data == "Joseph R. Biden, Jr."):
            return df["dem_" + col] 
        else: 
            return df["rep_" + col] 
        
    def rep_result(df, col="candidate"):
        if (df.rep_candidate == "Donald J. Trump"): 
            return df["rep_" + col] 
        else:
            return df["dem_" + col]
    
    dem_candidate = df.apply(lambda df: dem_result(df, col="candidate"))
    dem_vote = df.apply(lambda df: dem_result(df, col="vote"))
    dem_score = df.apply(lambda df: dem_result(df, col="score"))
    
    rep_candidate = df.apply(lambda df: rep_result(df, col="candidate"))
    rep_vote = df.apply(lambda df: rep_result(df, col="vote"))
    rep_score = df.apply(lambda df: rep_result(df, col="score"))

    return pd.DataFrame({"year": df.year, "county": df.county,
                         "dem_candidate": dem_candidate, "dem_vote": dem_vote, "dem_score": dem_score,
                         "rep_candidate": rep_candidate, "rep_vote": rep_vote, "rep_score": rep_score})

In [201]:
dem_results(election_results.dem_candidate[1:10])

AttributeError: 'str' object has no attribute 'dem_candidate'

In [197]:
dem_results()

AttributeError: 'Series' object has no attribute 'dem_candidate'

In [ ]:
elections_results.dem_candidate.apply(lambda )

In [202]:
election_results.to_csv('data/election_results_na.csv', index=False)

In [203]:
election_results[election_results.county == "02070"]

,year,county,dem_candidate,dem_vote,dem_score,rep_candidate,rep_vote,rep_score
0,2016,02070,NA,NA,NA,NA,NA,NA
0,2020,02070,NA,NA,NA,NA,NA,NA

In [160]:
population_by_county.merge(election_results, by='county')

   a  b
0  1  3
1  2  4
0 -1  6
1  5  7

In [205]:
population_by_county[population_by_county.county == "02070"]

            GEO_ID                            NAME P2_001N P2_002N county
76  0500000US02070  Dillingham Census Area, Alaska    4857     146  02070

In [124]:
soup = BeautifulSoup(r.text)
#print(soup.prettify())
#print soup.find_all('tr')

table = soup.find("table", { "class" : "result" })

In [126]:
results_table = pd.read_html(str(table))[0]
last_col = len(results_table.columns)-1
    
popular_vote_pop = "Unnamed: " + str(last_col-1)
popular_vote_perc = "Unnamed: " + str(last_col)

In [131]:
len(results_table.columns)

11

4

In [119]:
from bs4 import BeautifulSoup
import requests

In [157]:
pd.DataFrame(res)

,dem_candidate,dem_vote,dem_score,rep_candidate,rep_vote,rep_score
0,"Joseph R. Biden, Jr.",97297.0,56.31%,Donald J. Trump,73480.0,42.53%

ValueError: If using all scalar values, you must pass an index

In [150]:
results#results.rename({'popular_vote_pop': 'Unnamed: 7', 'Unnamed: 9': 'popular_vote_perc'})

              candidate       party  popular_vote_pop popular_vote_perc
0       Donald J. Trump  Republican            5859.0            71.43%
1  Joseph R. Biden, Jr.  Democratic            2243.0            27.34%

In [32]:

results

              candidate       party  popular_vote_pop popular_vote_perc
0       Donald J. Trump  Republican            5859.0            71.43%
1  Joseph R. Biden, Jr.  Democratic            2243.0            27.34%